Coin/urls.py
from django.contrib import admin
from django.urls import path,include
from chat import views
from customer import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('account/', include('account.urls')),
    path('myadmin/',include('myadmin.urls')),
    path('customer/',include('customer.urls')),
    path('',views.HomePage),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-room-list/', views.chat_room_list, name='admin'),
    path('chat-room/<str:uuid>/', views.room, name='room'),
    path('chat-room/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py

import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from account.models import User

from .models import Room


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'room created'})

def chat_room_list(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat_room_list.html', {
        'rooms': rooms,
        'users': users
    })

@login_required(login_url='/account/login/')
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })

@login_required(login_url='/account/login/')
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
                
        messages.success(request, 'The room was deleted!')

        return redirect('/chat/chat-room-list/')
    else:
        messages.error(request, 'You don\'t have access to delete rooms!')

        return redirect('/chat/chat-room-list/')

chat/templates/chat/partials/chat_bubble.html
{% load static %}
<style>
    .hidden {
        display: none;
    }

    .chat {
        max-width: 300px;
        position: fixed;
        right: 10px;
        bottom: 20px;
        background: #eee;
        border: 2px solid #BA8864;
        border-radius: .5rem;
        padding: 4px;
    }

    .chat_icon {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 50px;
        border: none;
        outline: none;
        border-radius: 50%;
    }

    .chat_icon i {
        color: #BA8864;
        font-size: 3rem;
    }

    .chat_input {
        padding: 0.5rem 1.5rem;
        margin-bottom: 1rem;
        border-radius: 0.75rem;
        width: 95%;
        text-transform: none;
        color: #000000;
        background-color: #F3F4F6;
    }

    .chat_join_btn {
        padding: 0.5rem 1.5rem;
        border-radius: 0.75rem;
        color: #ffffff;
        background: #BA8864;
        border: none;
        outline: none;
        margin-bottom: 1rem;
        margin-left: .5rem;
    }

    .chat-container {
        background-color: #BA8864;
        display: flex;
        flex-direction: column;
        padding: 1rem 0 1rem 1rem;
        gap: 1.5rem;
        margin-bottom: 2rem;
        border-radius: .5rem;
    }

    .chat-container .sector {
        display: flex;
        align-items: center;
    }

    .chat-container .sector h1 {
        text-transform: none;
        font-size: 1.7rem;
    }

    .chat-container .sector img {
        width: 3rem;
        height: 3rem;
    }

    .chat-container p {
        text-transform: none;
    }

    .chat_room {
        overflow: scroll;
        padding: 1rem;
        margin-bottom: 1rem;
        border-radius: 0.75rem;
        background-color: #F3F4F6;
        height: 300px;
    }

    .chat_message_input {
        padding: 1rem;
        margin-bottom: 1rem;
        border-radius: 0.75rem;
        width: 100%;
        background-color: #F3F4F6;
        color:#000000;
    }

    .chat_message_submit {
        padding: 0.5rem 1.5rem;
        border-radius: 0.75rem;
        color: #ffffff;
        background:#BA8864;
        border:none;
        outline: none;
        margin-bottom: 1rem;
    }
</style>
<div id="chat" class="chat">
    <div id="chat_icon">
        <button id="chat_open" class="chat_icon">
            <i class="fa-solid fa-headset"></i>
            <!-- <img src="{% static 'chat.svg' %}" /> -->
        </button>
    </div>

    <div id="chat_welcome" class="hidden">
        <div class="chat-container">
            <div class="sector">
                <h1>Hi there</h1>
                <img src="{% static 'images/hand.png' %}">
            </div>
            <p>Need help? Search our help center for answers or start a conversation:</p>
        </div>

        <center><input type="text" name="name" id="chat_name" class="chat_input" placeholder="Your name..."></center>

        <button id="chat_join" class="chat_join_btn">Join chat</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="chat_room">
            <p style="color:#000000;text-transform: none;">Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="chat_message_input"
            placeholder="Type your message...">
        <button id="chat_message_submit" class="chat_message_submit">Send</button>
    </div>
</div>

chat/templates/chat/partials/room_list.html
<style>
    .room-container {
        display: grid;
        grid-template-columns: repeat(4, minmax(0, 1fr));
        gap: 1rem;
    }

    .join-btn {
        display: inline-block;
        padding: 0.5rem 1.5rem;
        margin-top: 1rem;
        border-radius: 0.75rem;
        color: #ffffff;
        background: green;
    }

    .delete-btn {
        display: inline-block;
        padding: 0.5rem 1.5rem;
        background: red;
        margin-top: 1rem;
        border-radius: 0.75rem;
        color: #ffffff;
    }
</style>
<div class="room-container">
    {% for room in rooms %}
    {% if room.status == 'waiting' %}
    <div style="padding: 1rem; border-radius: 0.75rem; background:#5cd2c6;">
        <h3 style="margin-bottom: 1rem;font-size: 1.125rem;line-height: 1.75rem;color:#000;">Chat</h3>
        <p style="color:#000;">
            <b>ID: </b>{{ room.uuid }}<br>
            <b>Name: </b>{{ room.client }}<br>
            <b>Status: </b>{{ room.get_status_display }}<br>
            <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
        </p>
        <a href="{% url 'chat:room' room.uuid %}" class="join-btn">Join</a>
        <a href="{% url 'chat:delete_room' room.uuid %}" class="delete-btn">Delete</a>
    </div>
    {% elif room.status == 'active' %}
    <div style="padding: 1rem; border-radius: 0.75rem; background-color: #dfe3ee; ">
        <h3 style="margin-bottom: 1rem;font-size: 1.125rem;line-height: 1.75rem; color:#000;">Chat</h3>
        <p style="color:#000;">
            <b>ID: </b>{{ room.uuid }}<br>
            <b>Name: </b>{{ room.client }}<br>
            <b>Status: </b>{{ room.get_status_display }}<br>
            <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
        </p>
        <a href="{% url 'chat:room' room.uuid %}" class="join-btn">Join</a>
        <a href="{% url 'chat:delete_room' room.uuid %}" class="delete-btn">Delete</a>
    </div>
    {% else %}
    <div style="padding: 1rem; border-radius: 0.75rem; background-color: #363753; ">
        <h3 style="margin-bottom: 1rem;font-size: 1.125rem;line-height: 1.75rem;color:#fefefe; ">Chat</h3>
        <p style="color:#fefefe;">
            <b>ID: </b>{{ room.uuid }}<br>
            <b>Name: </b>{{ room.client }}<br>
            <b>Status: </b>{{ room.get_status_display }}<br>
            <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
        </p>
        <a href="{% url 'chat:room' room.uuid %}" class="join-btn">Join</a>
        <a href="{% url 'chat:delete_room' room.uuid %}" class="delete-btn">Delete</a>
    </div>
    {% endif %}
    {% endfor %}
</div>